MySQLServer: ''
MySQLPort: 3306
MySQLDatabase: ''
MySQLOption: '?allowPublicKeyRetrieval=true&useSSL=false'
MySQLUsername: ''
MySQLPassword: ''

useSQL: true

SQLiteLocation: 'server.data'

GraveTime: 360
GraveCacheWarning: true

DiscordURL: 'https://discord.gg/MEYEPgN3T6'

announceTime: 60